# Generated by Django 5.2.8 on 2026-02-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap_data',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
